# roles/example/tasks/HAProxy.yml
- name: configure HAProxy
  gather_facts: false
  tasks:
    - name: prep the firewall
      ansible.posix.firewalld:
        port: 8181/tcp
        port: 443/tcp
        port: 80/tcp
        permanent: yes
        state: enabled
    - name: add group
      group:
        name: HA
        comment: service group for HAProxy
        state: present
    - name: add users
      user:
        name: haproxy
        comment: service account for apache
        group: HA
        state: present
    - name: install HAProxy
      yum:
        name: haproxy
        state: present