---
- name: configuring my keys
  gather_facts: false
  hosts: all
  tasks:
    - name: adding authorized key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    - name: rebooting everything
      reboot:
        reboot_timeout: 300
- name: configure the web servers
  gather_facts: false
  hosts: web
  tasks:
    - name: configure web role
      import_role:
        name: role_web
    - name: copy the index files over
      copy:
        src: /root/GitHub/ansible_tutorial_repo/FinalAnsibleProject/web_files/*
        dest: /var/www/html/*
        owner: apache
        group: web
        mode: '550'
        follow: true
    - name: start the apache web services
      systemd:
        name: httpd
        enabled: true
        state: started
- name: configure HAProxy
  gather_facts: false
  hosts: HA
  tasks:
    - name: configure HA role
      import_role:
        name: role_HAProxy
    - name: copy HA config
      copy:
        src: /root/GitHub/ansible_tutorial_repo/FinalAnsibleProject/configs/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: haproxy
        group: root
        mode: '550'
        follow: true
    - name: add systemd unit for haproxy
      systemd:
        name: haproxy
        enabled: true
        state: started
- name: configure the DB Server
  gather_facts: false
  hosts: DB
  vars:
    mysql_root_password: "{{ vault_mysql_password }}"
  tasks:
    - name: install mysql
      yum:
        name: mysql
        state: present
- name: Start the db services
  gather_facts: false
  hosts: DB
  tasks:
    - name: start the db server
      systemd:
        enabled: true
        state: started
        name: mariadb-server
- name: create the database
  hosts: DB
  tasks:
    - name: create the database
      mysql_db:
        login_user: "{{ vault_mysql_name }}"
        login_password: "{{ vault_mysql_password }}"
        login_host: "{{ vault_login_host }}"
        name: wordpress
        state: present
- name: create the db_user
  hosts: DB
  tasks:
    - name: remove any anonymous user
        mysql_user:
        name: ''
        host: localhost
        state: absent
        login_user: "{{ vault_mysql_name }}"
        login_password: "{{ vault_mysql_password }}"
        login_host: "{{ vault_login_host }}"
    - name: add my user
      mysql_user:
        login_user: "{{ vault_mysql_name }}"
        login_password: "{{ vault_mysql_password }}"
        login_host: "{{ vault_login_host }}"
        name: "{{ vault_login_name }}"
        password: "{{ vault_login_password }}"
        priv: '*.*:ALL'
        state: present
- name: install the flask restful module
  hosts: DB
  tasks:
    - name: add the flask user account
      user:
        name: flask
    - name: configure the flask role
      import_role:
        name: role_flask
    - name: copy the flask files
      copy:
        src: '/root/GitHub/ansible_tutorial_repo/FinalAnsibleProject/web_files/*.py'
        dest: '/var/FlaskRestful/'
        owner: flask
        mode: '550'
- name: set the username and password as env vars
  hosts: DB
  tasks:
    - name: set the username
      shell: db_username={{ vault_mysql_username }}
    - name: set the password
      shell: db_password={{ vault_mysql_password }}
- name: export the variables I need
  hosts: DB
  tasks:
    - name: set the vars to be persistent
      shell: export db_username; export db_password
- name: configure the restful_service
  hosts: DB
  tasks:
    - name: copy the systemd unit file
      copy:
        src: /root/GitHub/ansible_tutorial_repo/FinalAnsibleProject/config/flask_restful.service
        dest: /etc/systemd/system/flask_restful.service
        mode: '550'
    - name: enable the systemd unit file
      shell: enable flask_restful.service; start flask_restful.service
- name: configure the database tables
  hosts: DB
  tasks:
    - name: copy the sql script
      copy:
        src: /root/GitHub/ansible_tutorial_repo/FinalAnsibleProject/config/create_table.sql
        dest: /var/FlaskRestful/
        owner: 'flask'
        mode: '550'
    - name: execute the script
      shell: mysql -u {{ vault_login_username }} -p {{ vault_login_host }} -h  {{ vault_login_host }} < /var/FlaskRestful.sql