---
# roles/example/tasks/install_flask.yml
- name: install the flask restful modules
  tasks:
    pip: 
      name: flask flask-restful pyodbc PyMySQL
- name: set the firewall
  tasks:
    - ansible.posix.firewalld:
        port: 80/tcp
        state: enabled
        permanent: true
