# roles/example/tasks/HAProxy.yml
- name: prep the firewall
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 8181/tcp
    - 443/tcp
    - 80/tcp
- name: add group
  group:
    name: HA
    comment: service group for HAProxy
    state: present
- name: add users
  user:
    name: haproxy
    comment: service account for apache
    group: HA
    state: present
- name: install HAProxy
  yum:
    name: haproxy
    state: present
